### PR TITLE
Proposed handling of google drive sync error

### LINKED ISSUE #7: Error pops up if you dont have a folder for play books notes on your google drive
I got your app up and running, but before I actually downloaded playbooks and saved quotes (which generated the folder "Play Books Notes" on my google drive), I was getting an error:

UnboundLocalError: local variable 'notes_folder_id' referenced before assignment.

The error went away after installing play books, saving quotes, and syncing to my google drive. I didn't lose too much time on it, luckily saving quotes was the first thing I tried to fix it, but just a heads up that a more informative printout when this exception pops up might help people. Or a comment in the readme that you must have some quotes saved in your play books and your play books synced to your drive for this to work. Maybe its obvious to other people and its just me that tripped over this. Really nice app you have here I am poking around to see if I can contribute. I have some flask experience, but overall am pretty new to programming.

### PR DESCRIPTION
**Pull request by brettvanderwerff**
I took a crack at some simple handling of the drive sync error. The error template is flexible and can take whatever error you want in the future. My front end knowledge is not great, so I just tried to keep the formatting consistent with what you had done. This worked well before the recent shift to docker, I have not been able to test it since then. Feel free to ignore this if you don't like the suggestion. 

Closes #7
Related to #8

### CODE REVIEW

**Comment by mammuth** [comment]
Cool! :tada:

Two thoughts:
- I think we should just add a section to the base template which renders an error which is given to the context. This way we have the displaying of errors at one place only and all child templates can use it (if you want to make it fancy, in the bulma docs (the CSS framework I used) you find Infos about predefined components). Does flask have a message framework (I mostly use django which does have one)? Then this could be used.
- It would be more expressive if the notes module would define custom exceptions and would throw them instead of the generic drive exceptions.

**Comment by brettvanderwerff** [comment]
Ill try to research how do do this, I'm pretty new to flask though if it is taking too long move on without me on this one.

**Review by mammuth — CHANGES_REQUESTED** [review]
- Create explicit exceptions which the notes module throws
- Add error details to context (eg `'messages': [{'type': 'error', 'description': 'spam and eggs']`)
- render messages (probably) in base template using highlighting of the CSS framework (according to the message type: error -> red box, success -> green box for example)

**Comment by brettvanderwerff** [comment]
The more elegant error handling you are looking for is a bit beyond me at this point. I may have to come back to this when I know more.

**Comment by mammuth** [comment]
> The more elegant error handling you are looking for is a bit beyond me at this point. I may have to come back to this when I know more.

Alright, I'll show it to you! 😊

**Comment by mammuth** [comment]
Closing in favor of #16

**Pull request closed without merging**
